# Generated by Django 3.2.5 on 2021-08-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function_view', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
