# Generated by Django 3.2.5 on 2021-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('descripion', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
